#pragma once
#include <random>
#include <vector>

#include "Order.hpp"

namespace Trading {

/// Market scenarios with different volatility levels for testing the trading engine
enum class MarketScenario : uint8_t { NORMAL, HIGH_VOLATILITY, BULL_MARKET, BEAR_MARKET, FLASH_CRASH };

class MarketSimulator {
private:
    std::mt19937 m_rng{42};  /// Using a fixed seed for reproducibility in tests
    OrderId m_nextOrderId{5000};

public:
    /// Generate a order feed based on specified market scenario and security id
    std::vector<Order> generateScenarioData(MarketScenario scenario, SecurityId securityId, uint32_t orderCount) {
        std::vector<Order> syntheticFeed;
        syntheticFeed.reserve(orderCount);

        double baselinePrice = 100.0;
        std::normal_distribution<double> priceDelta(
            0.0, 0.5);  /// Standard variance for normal market conditions, found through empirical testing to produce
                        /// realistic price movements

        /// Dynamically adjust volatility based on the market scenario
        if (scenario == MarketScenario::HIGH_VOLATILITY) {
            priceDelta = std::normal_distribution<double>(
                0.0, 3.0);  /// Extreme swings for a high volatility for rapid price changes
        }

        for (uint32_t i = 0; i < orderCount; ++i) {
            /// Walking prices are generated by adding a small random delta to the previous price
            baselinePrice += priceDelta(m_rng);
            if (baselinePrice <= 1.0) baselinePrice = 1.0;  /// Enforce technical floor bounds

            /// Handle directional drift properties for specific trend profiles
            if (scenario == MarketScenario::BULL_MARKET) baselinePrice += 0.15;
            if (scenario == MarketScenario::BEAR_MARKET) baselinePrice -= 0.15;
            if (scenario == MarketScenario::FLASH_CRASH && i > (orderCount * 0.7)) {
                baselinePrice -= 4.0;  /// Simulate a sudden crash in the last 30% of the feed
            }

            Side side = (m_rng() % 2 == 0) ? Side::BUY : Side::SELL;
            uint32_t quantity = ((m_rng() % 10) + 1) *
                                100;  /// Randomized order sizes in multiples of 100 for realistic order book depth

            syntheticFeed.push_back(Order{.id = m_nextOrderId++,
                                          .timestamp = i * 1'000'000ULL,  /// Timeline tracking (in microseconds)
                                          .price = baselinePrice,
                                          .quantity = quantity,
                                          .securityId = securityId,
                                          .side = side,
                                          .type = OrderType::LIMIT});
        }

        return syntheticFeed;
    }
};
}  // namespace Trading
